### ISSUE TITLE
Adding datasets and models to the Hugging Face Hub

### ISSUE THREAD

**Issue by lvwerra** [alexa/massive#1]
Hi there!

Congratulations on releasing the MASSIVE dataset and benchmark - this is really exciting! 🎉  

Seeing that you already have a script to load the dataset with `datasets` I was wondering if you would like to directly host the dataset on the Hugging Face Hub? That would allow loading the dataset in a single line :`ds = load_dataset("amazon/massive")`.

There are already two organization where you could host it:
https://huggingface.co/AmazonScience
https://huggingface.co/amazon

In addition we could also add some baseline models e.g. the ones from the example script. 

What do you think? Happy to help adding them!

**Comment by jgmf-amazon** [comment]
Hi @lvwerra , yes, we plan to do this soon. I'll respond soon with an ETA. Thank you.

**Comment by qanastek** [comment]
Hi @jgmf-amazon, I uploaded a version MASSIVE close to the source schema [on HuggingFace](https://huggingface.co/datasets/qanastek/MASSIVE).

**Comment by qanastek** [comment]
Thank you, I am fixing it right now.

**Comment by qanastek** [comment]
I push a new version with the fix on [qanastek/MASSIVE](https://huggingface.co/datasets/qanastek/MASSIVE).

@lhoestq But I have a new error `config is not in the list`.  I have a DEFAULT_CONFIG_NAME already setup, so I don't really know from where it's come from :

```python
_ALL = "all"

class MASSIVE(datasets.GeneratorBasedBuilder):
    """MASSIVE: A 1M-Example Multilingual Natural Language Understanding Dataset with 51 Typologically-Diverse Languages"""

    BUILDER_CONFIGS = [
        datasets.BuilderConfig(
            name = name,
            version = datasets.Version("1.0.0"),
            description = f"The MASSIVE corpora for {name}",
        ) for name in _LANGUAGE_PAIRS        
    ]

    BUILDER_CONFIGS.append(datasets.BuilderConfig(
        name = _ALL,
        version = datasets.Version("1.0.0"),
        description = f"The MASSIVE corpora for entire corpus",
    ))

    DEFAULT_CONFIG_NAME = _ALL
```

**Comment by lhoestq** [comment]
The preview is working fine @qanastek thanks :)
The error message was a bug on our side

**Comment by qanastek** [comment]
License changed! https://huggingface.co/datasets/qanastek/MASSIVE

**Comment by cperiz** [comment]
Thanks but I don't see the update. Do you see it on your end @qanastek?

**Comment by qanastek** [comment]
Ok, sorry for the misunderstanding. It should be good now. I updated the [LICENSE file](https://huggingface.co/datasets/qanastek/MASSIVE/blob/main/LICENSE), [in code](https://huggingface.co/datasets/qanastek/MASSIVE/blob/main/MASSIVE.py#L40) license, dataset [card license](https://huggingface.co/datasets/qanastek/MASSIVE/blob/main/README.md#L60) and finally the [license section](https://huggingface.co/datasets/qanastek/MASSIVE#licensing-information).

**Comment by cperiz** [comment]
@lhoestq I incorporated the changes for preview fix in  the [AmazonScience](https://huggingface.co/datasets/AmazonScience/massive) version as well. Thanks for that. @qanastek thanks for the updates. I applied your updates to the one on AmazonScience, except the bio tags (since that is not part of the original dataset). Let me check with the team on this.
