### ISSUE TITLE
Can anyone reproduce the baseline results reported in the paper with the current version of codes?

### ISSUE THREAD

**Issue by bozheng-hit** [alexa/massive#21]
I think the following codes should be inserted here: https://github.com/alexa/massive/blob/main/src/massive/utils/training_utils.py#L472

```
for i, x in enumerate(lab): 
    if x == -100: 
        pred[i] = -100
```

**Comment by bozheng-hit** [comment]
I am able to reproduce the results after adding the above codes.
I strongly suggest the contributors at least run the codes for one time before committing.

**Comment by jgmf-amazon** [comment]
Please re-open if you still see the problem. Thank you!
