### ISSUE TITLE
Does Label Truncation Influence the Results?

### ISSUE THREAD

**Issue by FeiWang96** [alexa/massive#25]
Hi,

It seems that labels for testing are also truncated to a fixed max length: https://github.com/alexa/massive/blob/cfe86f6352ca998f14fa98235fdee93407266b60/src/massive/loaders/collator_t2t_ic_sf.py#L91 
If the input sequence for encoder-only models or label sequence for generative models are longer than max length, additional labels will be ignored during evaluation. (Although samples in this dataset are relatively short sentences, it is still a risk.)
I think a better way could be to maintain an independent evaluation tool taking the predictions and raw labels as inputs.

**Comment by jgmf-amazon** [comment]
Hi @FeiWang96 , I agree that this shouldn't be an issue with the dataset as it stands, but maybe could be in the future. In general, we recommend using [eval.ai](https://eval.ai/web/challenges/challenge-page/1697/leaderboard) for "official" test results. The eval.ai setup evaluation code does not perform any tokenization, so it would not fall prey to this issue.

Alternatively, you could call [`eval_preds`](https://github.com/alexa/massive/blob/5a31faa8bdae91b6f3877f36b3aa59d017403a5a/src/massive/utils/training_utils.py#L427), which can also operate on string inputs. This is the same function that eval.ai uses under the hood.

**Comment by FeiWang96** [comment]
Thanks @jgmf-amazon !
