### ISSUE TITLE
Number of parameters limit

### ISSUE THREAD

**Issue by maximedb** [alexa/massive#30]
Thank you for organizing this interesting shared task!

What is the parameters limit for decoder-only models? They also use the text-to-text approach, but resemble the decoder-only architecture...

Thank you,

Maxime.

**Comment by jgmf-amazon** [comment]
Hi @maximedb , ah, yes, evidently we didn't specify. Sorry for the miss. For MMNLU, let me speak with the other organizers and get back tomorrow.

Please note that for the [MASSIVE leaderboard](https://eval.ai/web/challenges/challenge-page/1697/overview) there is no parameter limit--only for the MMNLU "Phase". Thanks.

**Comment by jgmf-amazon** [comment]
Hi @maximedb , let's go with the same limit as for encoders, 350M parameters, including embeddings.
