### ISSUE TITLE
Unable to prepare data

### ISSUE THREAD

**Issue by gurnoor6** [alexa/massive#33]
Preparing the dataset using the command mentioned in the README throws a TypeError.
```
python scripts/create_hf_dataset.py -d /path/to/jsonl/files -o /output/path/and/prefix
```

Traceback of the error:
```
...
Adding numeric intent and slot labels to the datasets
100%|████████████████████████████████████████████████████████████████████████████| 587214/587214 [01:05<00:00, 8946.88ex/s]
100%|████████████████████████████████████████████████████████████████████████████| 103683/103683 [00:11<00:00, 8882.30ex/s]
100%|████████████████████████████████████████████████████████████████████████████| 151674/151674 [00:17<00:00, 8832.28ex/s]
Traceback (most recent call last):
  File "/path/to/massive/scripts/create_hf_dataset.py", line 331, in <module>
    main()
  File "/path/to/massive/scripts/create_hf_dataset.py", line 325, in main
    ds_creator.add_numeric_labels()
  File "/path/to/massive/scripts/create_hf_dataset.py", line 259, in add_numeric_labels
    if self.hidden_eval[0]['intent_str']:
TypeError: 'NoneType' object is not subscriptable
```

jsonl files used to prepare dataset contain the MASSIVE dataset downloaded from this link: https://amazon-massive-nlu-dataset.s3.amazonaws.com/amazon-massive-dataset-1.0.tar.gz

The error is arising because the dataset mentioned above does not contain MMNLU-22 eval data. Either the README should be updated to clarify that the jsonl path in the `create_hf_dataset.py` script should contain the MMNLU eval data as well, or alternatively the line 259-260 in `scripts/create_hf_dataset.py` can be modified to the following:
```
if self.hidden_eval and self.hidden_eval[0]['intent_str']:
    self.hidden_eval = self.hidden_eval.map(create_numeric_labels)
```
instead of the current
```
if self.hidden_eval[0]['intent_str']:
    self.hidden_eval = self.hidden_eval.map(create_numeric_labels)
```

**Comment by cperiz** [comment]
Thanks a lot @gurnoor6 for flagging this. We've had the fix offline. Created the PR [here](https://github.com/alexa/massive/pull/34). Will notify here once merged.

**Comment by cperiz** [comment]
@gurnoor6 [PR](https://github.com/alexa/massive/pull/34) is merged. Closing this. But please feel free to re-open if you face any issue.
