### ISSUE TITLE
Preparing data 

### ISSUE THREAD

**Issue by khieu** [alexa/massive#8]
I prepare the MASSIVE dataset using the following script

```
python scripts/create_hf_dataset.py -d /path/to/jsonl/files -o /output/path/and/prefix
```

which result in the following error

```
Traceback (most recent call last):
  File "scripts/create_hf_dataset.py", line 310, in <module>
    main()
  File "scripts/create_hf_dataset.py", line 301, in main
    ds_creator.create_datasets(args.massive_data_paths)
  File "scripts/create_hf_dataset.py", line 84, in create_datasets
    for line in f:
  File "/scratch/hle/conda_env/py3_env/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa3 in position 37: invalid start byte

```

Also, the `jsonl` files seem to be encoded and cannot be viewed as shown in the README.

Any suggestion to resolve the issue is greatly appreciated!

**Comment by khieu** [comment]
I see 👍 . I just went ahead and manually move the `._<locale>.jsonl` files. Thanks!

**Comment by cperiz** [comment]
@khieu @wenh06 Thanks a lot for pointing out the existence of the ._*.jsonl files in our tarball. We've now re-uploaded the tarball with the hidden files removed, so it should fix the issue you faced. Please feel free to reopen in case it still exists. Thanks.
